/**
 * Sample data — Supabase холбогдох хүртэл түр ашиглах
 * Phase 2-д энэ нь database query-ээр солигдоно
 */
import type { Product } from "@/components/customer/ProductCard";

export const bestSellers: Product[] = [
  {
    id: "1",
    category: "Даршилсан ногоо",
    title: "Даршилсан өргөст хэмх, 720мл",
    price: 8500,
    oldPrice: 10000,
    rating: 4.8,
    reviewCount: 240,
    emoji: "🥒",
    bg: "bg-gradient-to-br from-[#f0f7d8] to-[#d6e88a]",
    tag: "discount",
    tagText: "−15%",
  },
  {
    id: "2",
    category: "Чанамал",
    title: "Гүзээлзгэний чанамал, 450г",
    price: 12900,
    rating: 4.9,
    reviewCount: 180,
    emoji: "🍓",
    bg: "bg-gradient-to-br from-[#fde6e6] to-[#fbc4c4]",
    tag: "bio",
    tagText: "BIO",
  },
  {
    id: "3",
    category: "Хүүхдийн тэжээл",
    title: "Алим-луувангийн нухаш, 200г",
    price: 4500,
    rating: 5.0,
    reviewCount: 95,
    emoji: "👶",
    bg: "bg-gradient-to-br from-[#fff2e9] to-[#ffd9c0]",
    tag: "new",
    tagText: "ШИНЭ",
  },
  {
    id: "4",
    category: "Компот",
    title: "Чавганы компот, 1л",
    price: 9900,
    oldPrice: 11000,
    rating: 4.7,
    reviewCount: 130,
    emoji: "🍑",
    bg: "bg-gradient-to-br from-[#f5efe3] to-[#e6d8be]",
    tag: "discount",
    tagText: "−10%",
  },
];

export const newArrivals: Product[] = [
  {
    id: "5",
    category: "Ногооны салат",
    title: "Лоолийн салат, 500г",
    price: 7200,
    rating: 4.6,
    reviewCount: 22,
    emoji: "🥗",
    bg: "bg-gradient-to-br from-[#f0f7d8] to-[#b5d33d]",
    tag: "new",
    tagText: "ШИНЭ",
  },
  {
    id: "6",
    category: "Чанамал",
    title: "Үхрийн нүдний чанамал, 450г",
    price: 14500,
    rating: 4.8,
    reviewCount: 18,
    emoji: "🫐",
    bg: "bg-gradient-to-br from-[#fde6e6] to-[#fbc4c4]",
    tag: "new",
    tagText: "ШИНЭ",
  },
  {
    id: "7",
    category: "Бэлгийн багц",
    title: "VIDAN Премиум багц (5 ширхэг)",
    price: 45000,
    rating: 5.0,
    reviewCount: 12,
    emoji: "🍯",
    bg: "bg-gradient-to-br from-[#fff8d8] to-[#ffe899]",
    tag: "bio",
    tagText: "BIO",
  },
  {
    id: "8",
    category: "Хүүхдийн тэжээл",
    title: "Алим-чавганы нухаш, 200г",
    price: 4800,
    rating: 4.9,
    reviewCount: 30,
    emoji: "🍎",
    bg: "bg-gradient-to-br from-[#fff2e9] to-[#ffd9c0]",
    tag: "new",
    tagText: "ШИНЭ",
  },
];

export const categories = [
  { emoji: "🥒", name: "Даршилсан ногоо", count: 12 },
  { emoji: "🫙", name: "Чанамал", count: 8 },
  { emoji: "🥤", name: "Компот", count: 6 },
  { emoji: "🍎", name: "Алимны нухаш", count: 4 },
  { emoji: "👶", name: "Хүүхдийн тэжээл", count: 5 },
  { emoji: "🎁", name: "Бэлгийн багц", count: 3 },
];
